# Generated by Django 2.2.5 on 2019-11-16 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('content', models.TextField(blank=True, verbose_name='Содержимое')),
                ('active', models.BooleanField(blank=True, default=False, null=True)),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('slug', models.SlugField(max_length=30, unique=True, verbose_name='url отметка')),
                ('like', models.PositiveIntegerField(blank=True, default=0, verbose_name='Лайки')),
                ('dislike', models.PositiveIntegerField(blank=True, default=0, verbose_name='Дизлайки')),
                ('views', models.PositiveIntegerField(blank=True, default=True, null=True, verbose_name='Просмотры')),
                ('author', models.ForeignKey(on_delete='PROTECT', related_name='postAuthor', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200, verbose_name='Содержимое')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Опубликован')),
                ('like', models.PositiveIntegerField(blank=True, default=0, verbose_name='Лайки')),
                ('views', models.PositiveIntegerField(blank=True, default=0, verbose_name='Просмотры')),
                ('dislike', models.PositiveIntegerField(blank=True, default=0, verbose_name='Дизлайки')),
                ('author', models.ForeignKey(on_delete='PROTECT', related_name='commentAuthor', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='postComment', to='core.Post', verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
